spring:
  data:
    mongodb:
      database: graduation-project-document
      host: localhost
      port: 27017
  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}


    properties:
      email:
        smtp:
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
kafka:
  raw-event:
    topic: rawEvents

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs